[package]
name = "ex_text_splitter"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ex_text_splitter"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
text-splitter = "0.10.0"

[features]
markdown = ["text-splitter/markdown"]
